---
- name: Set solr_filename for Solr >=5.x.
  set_fact:
    "solr_filename=solr-{{ solr_version }}"
  when: "solr_version.split('.')[0] == '5'"

- name: Download Solr.
  get_url:
    url: "{{ solr_mirror }}/lucene/solr/{{ solr_version }}/{{ solr_filename }}.tgz"
    dest: "{{ solr_workspace }}/{{ solr_filename }}.tgz"
    force: no

- name: Expand Solr.
  command: >
    tar -C {{ solr_workspace }} -xvzf {{ solr_workspace }}/{{ solr_filename }}.tgz
    creates={{ solr_workspace }}/{{ solr_filename }}/bin/solr

- name: Check if Solr is already installed.
  stat: "path={{ solr_install_path }}/bin/solr"
  register: solr_file

- name: Run install_solr_service.sh 
  command: "{{ solr_workspace }}/{{ solr_filename }}/bin/install_solr_service.sh {{ solr_workspace }}/{{ solr_filename }}.tgz -p {{ solr_port }} -s {{ solr_service_name }} -u {{ solr_user }}"
  when: not solr_file.stat.exists 

- include: create_core.yml
  with_items: '{{ solr_cores }}'

- name: Set hostname
  lineinfile: dest=/etc/default/{{ solr_service_name }}.in.sh regexp=^SOLR_HOST= line='SOLR_HOST="{{ solr_host }}"'
  notify: restart solr
